services:
  auth:
    build:
      context: ./auth
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      web:
        condition: service_started
      api:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-network
  
  web:
    build:
      context: ./web
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

  api:
    build:
      context: ./api
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
