services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      web:
        condition: service_started
      api:
        condition: service_started
    restart: unless-stopped
  
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped

  api:
    build:
      context: ./api
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:5000
